[EventReference] Fixed Error CS0173
Error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'GenericScriptableArchitecture.ScriptableEvent' and 'GenericScriptableArchitecture.EventInstancer'